### ISSUE TITLE
Expose Chart instance

### ISSUE THREAD

**Issue by Sironfoot** [earlonrails/angular-chartjs-directive#1]
Thanks for this directive. Really saved my bacon as I struggled with using Chart.js with Angular.

Just one thing, any chance you could expose the Chart object itself in some way. I need it to access functions on the chart instance such as generateLegend() e.g.

``` javascript
$scope.legendHtml = $sce.trustAsHtml($scope.myChart.chartInstance.generateLegend());
```

**Comment by Sironfoot** [comment]
After some fiddling I came up with the following. I modified the two $watch callbacks to send the chartInstance to a function you define when initialising the chart. So in the directive:

``` javascript
scope.$watch(
    function () {
        return scope.chartObject;
    },
    function (value) {
        if(!value) return;
        var chartType = options.type;
        var chartInstance = chart[chartType](scope.chartObject.data, scope.chartObject.options);

        if (scope.chartObject.chartReady) {
            scope.chartObject.chartReady(chartInstance);
        }
});
```

...and in my controller:

``` javascript
$scope.myChart = {
    data: myData,
    options: {
        legendTemplate: '...snip...'
    },
    chartReady: function (chartInstance) {
        $scope.legendHtml = $sce.trustAsHtml(chartInstance.generateLegend());
    }
};
```

I'm new to AngularJS, so I'm not sure if it's the correct way of doing it, but it seems to work.

**Comment by earlonrails** [comment]
Glad you like the directive. The legendTemplate looks like it is an option that you can pass into the constructor, which is available via the chartObject with options as you have done in your code here. What do you end up doing with the legendHtml part? Just trying to understand this a bit more. I know this is old comment/issue.

**Comment by sagrath23** [comment]
Hi,

Another way to do this is using chart.js options, like this: 

``` javascript
$scope.myChart = {
    data: myData,
    options: {
        legendTemplate: '...snip...',
        onAnimationComplete: function(){
            $scope.legendHtml = $sce.trustAsHtml(this.generateLegend());
        }
    }
};
```

 without make any change in the directive.

**Comment by earlonrails** [comment]
Thanks @sagrath23 will close this issue.
