### ISSUE TITLE
scope.chartObject.data undefined

### ISSUE THREAD

**Issue by janigorse** [earlonrails/angular-chartjs-directive#5]
Hi, thanks for the directive, saved my work alot, I am using it with angular. I have one issue
though. I had to comment a block from line 28 to 33, because I was getting scope.chartObject.data undefined error. I guess this is because chart has no data yet. Could you include some checking
in the line 29? Or how should I check if chart has no data?

Best wishes,
Jani

**Comment by serenade2** [comment]
Hello, thank you for the directive,
I also have the same issue : TypeError: Cannot read property 'data' of undefined , @janigorse Did you find anyway to bypass this error to at least make the chart display?

**Comment by sagrath23** [comment]
Hi, 
 I use typeof to validate scope.chartObject in line 32, like this: 

``` javascript
if(typeof scope.chartObject !== 'undefined'){
     chart[chartType](scope.chartObject.data, scope.chartObject.options);
}
```

I hope that could help you.

**Comment by serenade2** [comment]
@sagrath23 , thank you it really help.
