### ISSUE TITLE
Flickering between charts after chart type is changed

### ISSUE THREAD

**Issue by anchovy** [earlonrails/angular-chartjs-directive#6]
Hi,

Great directive; thanks.

One issue I've noticed though is after changing the chart type - when you mouse over the chart, the 'previous version' of the chat sometimes becomes visible, hiding the 'new version', this can be seen in action on the demo page: http://earlonrails.github.io/angular-chartjs-directive/

Any ideas how to overcome this issue?

Thanks in advance.

**Comment by sagrath23** [comment]
Hi, 

I fixed this issue deleting the canvas that contains the old chart, and inserting a new one.
Try  to do this: 
 `element.empty();
                                element.append('<canvas></canvas>');` 

Just add these lines below line 37.

I hope that this could help you.

Cheers.

**Comment by anchovy** [comment]
Hi

Thanks the the tip @sagrath23, this didn't quite work for me, so I took this thought flow and changed it to:

`   var canvas, context, chart, options;

```
var init = function(c_type){

    element.empty();
    element.append('<canvas></canvas>'); 

    canvas  = element.find("canvas")[0];
    context = canvas.getContext("2d');

    options = {
        type:   c_type   || "Line",
        width:  attrs.width  || baseWidth,
        height: attrs.height || baseHeight,
        last_type: false
    };
    canvas.height = options.height;
    canvas.width = options.width;
    chart = new Chart(context);
}
init(attrs.type);
```

And then in the '//Update when charts data changes' watch function

```
//Update when charts data changes
scope.$watch(function() { return scope.chartObject; }, function(value) {
  if (!value) return;
  init(options.type);
  var chartType = options.type;
  chart[chartType](scope.chartObject.data, scope.chartObject.options);
  if (scope.chartInstance) scope.chartInstance.destroy();
  scope.chartInstance = chart[chartType](scope.chartObject.data, scope.chartObject.options);
}, true);
```

So it's setting up the vars initially - create the canvas element in the init function based on the default settings.

Then when the data changes - the init() function is called again, with the new type, and the canvas is re-generated, with no flickering.

**Comment by kkrauss-gpsw** [comment]
@anchovy care to submit a PR ?
